# Generated by Django 5.2.7 on 2025-11-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Store', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle or tagline', max_length=500)),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero/banner image', null=True, upload_to='homepage/')),
                ('featured_text', models.TextField(blank=True, help_text='Featured content or description')),
                ('is_active', models.BooleanField(default=True, help_text='Show this content on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
                'ordering': ['-updated_at'],
            },
        ),
    ]
