# Generated by Django 5.2.7 on 2025-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_5_product_material_orderinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main product image (will auto-populate from first uploaded image if not set)', null=True, upload_to='products/'),
        ),
    ]
